/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "lsys.y"

/* lsys.y - parser for L-systems.
 *
 * Copyright (C) 1990, Jonathan P. Leech
 *
 * This software may be freely copied, modified, and redistributed,
 * provided that this copyright notice is preserved on all copies.
 *
 * There is no warranty or other guarantee of fitness for this software,
 * it is provided solely "as is". Bug reports or fixes may be sent
 * to the author, who may or may not act on them as he desires.
 *
 * You may not include this software in a program or other software product
 * without supplying the source, or without informing the end-user that the
 * source is available for no extra charge.
 *
 * If you modify this software, you should include a notice giving the
 * name of the person performing the modification, the date of modification,
 * and the reason for such modification.
 *
 * $Log:	lsys.y,v $
 * Revision 1.3  91/03/20  10:33:14  leech
 * Support for G++.
 *
 * Revision 1.2  90/10/12  18:48:23  leech
 * First public release.
 *
 */

#undef YYSTYPE /* stop compilation errors */

#include <cstdlib>
#include <ctype.h>
#include <malloc.h>
#include "debug.h"
#include "Parser.h"

using LSys::LSysModel;
using LSys::Production;
using LSys::Value;
using LSys::Module;
using LSys::Expression;
using LSys::Predecessor;
using LSys::Successor;
using LSys::Name;

/* default version in liby:yyerror.o as extern "C" void yyerror(char *); */
void yyerror(char *);

/* lexical scanner (in lex.yy.o when automatically produced by lex) */
#include "lexdefs.h"
extern int yylex();

extern void lex_pushstate(int);
extern void lex_popstate();
extern int lexcol;
extern int lexline;

/* Return a pointer to the last string token parsed; in lexer */
extern char *lex_token();


// Dictionary & rule information needed/generated by the parser
LSysModel* parseInfo; // GLK

void set_parser_globals(LSysModel* m)
{
  parseInfo = m;
};


// A separate list of CF productions is maintained until all
//  productions have been read.
static LSys::List<Production> Context_free_rules;

// Should expressions be evaluated when read in?
static bool BindExpression = false;


#line 151 "lsys.tab.c"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "lsys.tab.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_ERROR = 3,                      /* ERROR  */
  YYSYMBOL_VALUE = 4,                      /* VALUE  */
  YYSYMBOL_INTEGER = 5,                    /* INTEGER  */
  YYSYMBOL_REAL = 6,                       /* REAL  */
  YYSYMBOL_FUNCTION = 7,                   /* FUNCTION  */
  YYSYMBOL_IGNORE = 8,                     /* IGNORE  */
  YYSYMBOL_INCLUDE = 9,                    /* INCLUDE  */
  YYSYMBOL_DEFINE = 10,                    /* DEFINE  */
  YYSYMBOL_YIELDS = 11,                    /* YIELDS  */
  YYSYMBOL_NAME = 12,                      /* NAME  */
  YYSYMBOL_START = 13,                     /* START  */
  YYSYMBOL_OR = 14,                        /* OR  */
  YYSYMBOL_AND = 15,                       /* AND  */
  YYSYMBOL_16_ = 16,                       /* '|'  */
  YYSYMBOL_17_ = 17,                       /* '&'  */
  YYSYMBOL_EQ = 18,                        /* EQ  */
  YYSYMBOL_NE = 19,                        /* NE  */
  YYSYMBOL_20_ = 20,                       /* '<'  */
  YYSYMBOL_LE = 21,                        /* LE  */
  YYSYMBOL_GE = 22,                        /* GE  */
  YYSYMBOL_23_ = 23,                       /* '>'  */
  YYSYMBOL_24_ = 24,                       /* '+'  */
  YYSYMBOL_25_ = 25,                       /* '-'  */
  YYSYMBOL_26_ = 26,                       /* '*'  */
  YYSYMBOL_27_ = 27,                       /* '/'  */
  YYSYMBOL_28_ = 28,                       /* '%'  */
  YYSYMBOL_29_ = 29,                       /* '^'  */
  YYSYMBOL_UMINUS = 30,                    /* UMINUS  */
  YYSYMBOL_31_ = 31,                       /* '!'  */
  YYSYMBOL_32_ = 32,                       /* '~'  */
  YYSYMBOL_33_n_ = 33,                     /* '\n'  */
  YYSYMBOL_34_ = 34,                       /* ':'  */
  YYSYMBOL_35_ = 35,                       /* '('  */
  YYSYMBOL_36_ = 36,                       /* ')'  */
  YYSYMBOL_37_ = 37,                       /* ','  */
  YYSYMBOL_YYACCEPT = 38,                  /* $accept  */
  YYSYMBOL_lsystem = 39,                   /* lsystem  */
  YYSYMBOL_40_1 = 40,                      /* $@1  */
  YYSYMBOL_lines = 41,                     /* lines  */
  YYSYMBOL_line = 42,                      /* line  */
  YYSYMBOL_43_2 = 43,                      /* $@2  */
  YYSYMBOL_44_3 = 44,                      /* $@3  */
  YYSYMBOL_45_4 = 45,                      /* $@4  */
  YYSYMBOL_46_5 = 46,                      /* $@5  */
  YYSYMBOL_47_6 = 47,                      /* $@6  */
  YYSYMBOL_names = 48,                     /* names  */
  YYSYMBOL_single_name = 49,               /* single_name  */
  YYSYMBOL_successors = 50,                /* successors  */
  YYSYMBOL_optional_successors = 51,       /* optional_successors  */
  YYSYMBOL_successor = 52,                 /* successor  */
  YYSYMBOL_probability = 53,               /* probability  */
  YYSYMBOL_predecessor = 54,               /* predecessor  */
  YYSYMBOL_55_7 = 55,                      /* $@7  */
  YYSYMBOL_center_list = 56,               /* center_list  */
  YYSYMBOL_right_list = 57,                /* right_list  */
  YYSYMBOL_modules = 58,                   /* modules  */
  YYSYMBOL_module = 59,                    /* module  */
  YYSYMBOL_arguments = 60,                 /* arguments  */
  YYSYMBOL_61_8 = 61,                      /* $@8  */
  YYSYMBOL_exprlist = 62,                  /* exprlist  */
  YYSYMBOL_optional_conditional = 63,      /* optional_conditional  */
  YYSYMBOL_64_9 = 64,                      /* $@9  */
  YYSYMBOL_conditional = 65,               /* conditional  */
  YYSYMBOL_expression = 66,                /* expression  */
  YYSYMBOL_value = 67,                     /* value  */
  YYSYMBOL_name = 68                       /* name  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_int8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  3
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   198

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  38
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  31
/* YYNRULES -- Number of rules.  */
#define YYNRULES  71
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  116

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   275


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      33,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    31,     2,     2,     2,    28,    17,     2,
      35,    36,    26,    24,    37,    25,     2,    27,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,    34,     2,
      20,     2,    23,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,    29,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,    16,     2,    32,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    18,    19,    21,    22,    30
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,   126,   126,   126,   138,   139,   142,   146,   145,   152,
     151,   161,   160,   172,   176,   175,   186,   185,   203,   204,
     207,   218,   228,   233,   236,   242,   251,   255,   254,   284,
     286,   290,   293,   296,   301,   304,   314,   313,   320,   323,
     334,   346,   351,   350,   357,   360,   362,   367,   369,   371,
     373,   375,   377,   379,   381,   383,   385,   387,   389,   391,
     393,   395,   397,   399,   401,   403,   405,   407,   410,   414,
     416,   420
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "ERROR", "VALUE",
  "INTEGER", "REAL", "FUNCTION", "IGNORE", "INCLUDE", "DEFINE", "YIELDS",
  "NAME", "START", "OR", "AND", "'|'", "'&'", "EQ", "NE", "'<'", "LE",
  "GE", "'>'", "'+'", "'-'", "'*'", "'/'", "'%'", "'^'", "UMINUS", "'!'",
  "'~'", "'\\n'", "':'", "'('", "')'", "','", "$accept", "lsystem", "$@1",
  "lines", "line", "$@2", "$@3", "$@4", "$@5", "$@6", "names",
  "single_name", "successors", "optional_successors", "successor",
  "probability", "predecessor", "$@7", "center_list", "right_list",
  "modules", "module", "arguments", "$@8", "exprlist",
  "optional_conditional", "$@9", "conditional", "expression", "value",
  "name", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-28)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
     -28,     1,   -28,   -28,    14,   -28,   -28,    -2,   -28,   -13,
     -28,   -28,   -28,   -28,   -28,    -5,    50,   -28,    50,    42,
      -3,   -28,   -28,   -10,   -28,   -28,    50,    50,    50,    50,
     117,   -28,   -10,   -28,   117,   -28,   -28,   -28,   -28,   -28,
     -28,   -28,   -28,   -28,    94,    50,    50,    50,    50,    50,
      50,    50,    50,    50,    50,    50,    50,    50,    50,    50,
      50,    18,   -28,    17,    53,    -2,    50,   -28,   132,   146,
     159,    74,   169,   169,    39,    39,    39,    39,    -9,    -9,
      55,    55,    55,   -28,   -28,   -28,   -28,    77,   -18,    21,
     117,    48,    54,   -28,   -28,    -2,   -28,   -28,   -28,   -28,
      50,   -28,   -28,   117,    66,   -28,    77,    67,    -2,   117,
      69,    37,   -28,   -28,   -28,   -28
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       2,     0,     5,     1,     3,     7,    34,     0,    71,     0,
      13,    14,     4,    16,    19,     0,     0,    11,     0,     0,
       0,     6,    33,    38,    69,    70,     0,     0,     0,     0,
       9,    68,    38,    34,    15,    34,     8,    18,    20,    36,
      35,    63,    64,    65,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,    67,     0,    44,    27,    41,    66,    47,    48,
      49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
      59,    60,    61,    62,    10,    12,    42,     0,    32,     0,
      40,     0,    26,    17,    23,     0,    34,    28,    30,    37,
       0,    45,    43,    46,     0,    34,    21,    32,    31,    39,
       0,     0,    22,    29,    25,    24
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int8 yypgoto[] =
{
     -28,   -28,   -28,   -28,   -28,   -28,   -28,   -28,   -28,   -28,
     -28,   -28,   -28,   -28,     0,   -28,   -28,   -28,   -28,    19,
     -27,    29,    93,   -28,   -28,   -28,   -28,   -28,   -14,    23,
      -4
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,     1,     2,     4,    12,    14,    61,    33,    18,    19,
      20,    37,    93,   106,    94,   105,    64,    88,    97,    98,
      15,    22,    40,    66,    89,    87,    91,   102,    30,    31,
      32
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_int8 yytable[] =
{
      13,     3,    95,    16,    34,    96,    63,     8,    65,     8,
       8,    23,    41,    42,    43,    44,    38,    57,    58,    59,
      60,    17,     5,     6,     7,    39,     8,     9,    21,     8,
      36,    68,    69,    70,    71,    72,    73,    74,    75,    76,
      77,    78,    79,    80,    81,    82,    83,    10,    11,     8,
      85,    84,    90,    24,    25,    24,    25,    99,   100,    23,
       8,    23,     8,    55,    56,    57,    58,    59,    60,   108,
     115,    24,    25,    26,   101,    26,    35,   103,   111,    27,
      28,    27,    28,    29,    60,    29,   109,    86,    92,   104,
      96,    23,    49,    50,    51,    52,    53,    54,    55,    56,
      57,    58,    59,    60,    23,   114,   112,    23,    45,    46,
      47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
      57,    58,    59,    60,   107,    62,   113,   110,     0,     0,
      67,    45,    46,    47,    48,    49,    50,    51,    52,    53,
      54,    55,    56,    57,    58,    59,    60,    46,    47,    48,
      49,    50,    51,    52,    53,    54,    55,    56,    57,    58,
      59,    60,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,    59,    60,    48,    49,    50,    51,
      52,    53,    54,    55,    56,    57,    58,    59,    60,    51,
      52,    53,    54,    55,    56,    57,    58,    59,    60
};

static const yytype_int8 yycheck[] =
{
       4,     0,    20,     7,    18,    23,    33,    12,    35,    12,
      12,    15,    26,    27,    28,    29,    20,    26,    27,    28,
      29,    34,     8,     9,    10,    35,    12,    13,    33,    12,
      33,    45,    46,    47,    48,    49,    50,    51,    52,    53,
      54,    55,    56,    57,    58,    59,    60,    33,    34,    12,
      33,    33,    66,     5,     6,     5,     6,    36,    37,    63,
      12,    65,    12,    24,    25,    26,    27,    28,    29,    96,
      33,     5,     6,    25,    26,    25,    34,    91,   105,    31,
      32,    31,    32,    35,    29,    35,   100,    34,    11,    35,
      23,    95,    18,    19,    20,    21,    22,    23,    24,    25,
      26,    27,    28,    29,   108,    36,   106,   111,    14,    15,
      16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
      26,    27,    28,    29,    95,    32,   107,   104,    -1,    -1,
      36,    14,    15,    16,    17,    18,    19,    20,    21,    22,
      23,    24,    25,    26,    27,    28,    29,    15,    16,    17,
      18,    19,    20,    21,    22,    23,    24,    25,    26,    27,
      28,    29,    16,    17,    18,    19,    20,    21,    22,    23,
      24,    25,    26,    27,    28,    29,    17,    18,    19,    20,
      21,    22,    23,    24,    25,    26,    27,    28,    29,    20,
      21,    22,    23,    24,    25,    26,    27,    28,    29
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,    39,    40,     0,    41,     8,     9,    10,    12,    13,
      33,    34,    42,    68,    43,    58,    68,    34,    46,    47,
      48,    33,    59,    68,     5,     6,    25,    31,    32,    35,
      66,    67,    68,    45,    66,    34,    33,    49,    68,    35,
      60,    66,    66,    66,    66,    14,    15,    16,    17,    18,
      19,    20,    21,    22,    23,    24,    25,    26,    27,    28,
      29,    44,    60,    58,    54,    58,    61,    36,    66,    66,
      66,    66,    66,    66,    66,    66,    66,    66,    66,    66,
      66,    66,    66,    66,    33,    33,    34,    63,    55,    62,
      66,    64,    11,    50,    52,    20,    23,    56,    57,    36,
      37,    26,    65,    66,    35,    53,    51,    59,    58,    66,
      67,    58,    52,    57,    36,    33
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    38,    40,    39,    41,    41,    42,    43,    42,    44,
      42,    45,    42,    42,    46,    42,    47,    42,    48,    48,
      49,    50,    51,    51,    52,    53,    53,    55,    54,    56,
      56,    57,    57,    58,    58,    59,    61,    60,    60,    62,
      62,    62,    64,    63,    63,    65,    65,    66,    66,    66,
      66,    66,    66,    66,    66,    66,    66,    66,    66,    66,
      66,    66,    66,    66,    66,    66,    66,    66,    66,    67,
      67,    68
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     0,     2,     2,     0,     3,     0,     4,     0,
       5,     0,     5,     1,     0,     3,     0,     6,     2,     0,
       1,     2,     2,     0,     4,     3,     0,     0,     3,     3,
       1,     2,     0,     2,     0,     2,     0,     4,     0,     3,
       1,     0,     0,     3,     0,     1,     1,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     3,     2,     2,     2,     3,     2,     1,     1,
       1,     1
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YYDPRINTF ((stderr, "yychar = '%c'.\n", yychar));
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* $@1: %empty  */
#line 126 "lsys.y"
        {
		      // Get lex into correct start condition
		      lex_pushstate(LEX_EXPRESSION);
		    }
#line 1304 "lsys.tab.c"
    break;

  case 3: /* lsystem: $@1 lines  */
#line 131 "lsys.y"
                    { // This ensures that CF productions are applied last,
		      //  since they are at the end of the list of productions.
		      parserRules.append(&Context_free_rules);
		      lex_popstate();
		    }
#line 1314 "lsys.tab.c"
    break;

  case 7: /* $@2: %empty  */
#line 146 "lsys.y"
                    { lex_pushstate(LEX_MODULE); }
#line 1320 "lsys.tab.c"
    break;

  case 8: /* line: IGNORE $@2 names '\n'  */
#line 148 "lsys.y"
                    { lex_popstate(); }
#line 1326 "lsys.tab.c"
    break;

  case 9: /* $@3: %empty  */
#line 152 "lsys.y"
                    { Value v;
                      if (!parserSymbolTable.lookup(Name((yyvsp[-1].name)), v))
                        parserSymbolTable.enter(Name((yyvsp[-1].name)), (yyvsp[0].expression)->evaluate(parserSymbolTable));
		      delete (yyvsp[0].expression);
		    }
#line 1336 "lsys.tab.c"
    break;

  case 11: /* $@4: %empty  */
#line 161 "lsys.y"
                    { lex_pushstate(LEX_MODULE);
		      // Bind starting list expressions according to symtab
		      BindExpression = true;
		    }
#line 1345 "lsys.tab.c"
    break;

  case 12: /* line: START ':' $@4 modules '\n'  */
#line 166 "lsys.y"
                    { BindExpression = false;
		      lex_popstate();
		      parserStart = (yyvsp[-1].moduleList);
		    }
#line 1354 "lsys.tab.c"
    break;

  case 14: /* $@5: %empty  */
#line 176 "lsys.y"
                    { lex_pushstate(LEX_EXPRESSION); }
#line 1360 "lsys.tab.c"
    break;

  case 15: /* line: ':' $@5 expression  */
#line 178 "lsys.y"
                    { lex_popstate();
		      std::cerr << "Evaluating expression: " << *(yyvsp[0].expression) << std::endl;
		      std::cerr << (yyvsp[0].expression)->evaluate(parserSymbolTable) << std::endl;
		      delete (yyvsp[0].expression);
		    }
#line 1370 "lsys.tab.c"
    break;

  case 16: /* $@6: %empty  */
#line 186 "lsys.y"
                    { lex_pushstate(LEX_MODULE); }
#line 1376 "lsys.tab.c"
    break;

  case 17: /* line: name $@6 ':' predecessor optional_conditional successors  */
#line 190 "lsys.y"
                    { lex_popstate();
		      Production *p = new Production(Name((yyvsp[-5].name)), (yyvsp[-2].predecessor), (yyvsp[-1].expression), (yyvsp[0].successors));
		      PDebug(PD_PARSER, std::cerr << "Parsed production: " << *p << std::endl);
		      if (p->context_free())
			Context_free_rules.append(p);
		      else
			parserRules.append(p);
		    }
#line 1389 "lsys.tab.c"
    break;

  case 20: /* single_name: name  */
#line 208 "lsys.y"
                    {
		      PDebug(PD_PARSER, std::cerr << "Ignoring name " << Name((yyvsp[0].name)) << std::endl);
		      parserIgnoreTable.enter(Name((yyvsp[0].name)), Value(1));
		    }
#line 1398 "lsys.tab.c"
    break;

  case 21: /* successors: successor optional_successors  */
#line 220 "lsys.y"
                    { (yyval.successors) = new LSys::List<Successor>;
		      (yyval.successors)->append((yyvsp[-1].successor));
		      (yyval.successors)->append((yyvsp[0].successors));
		      delete (yyvsp[0].successors);
		    }
#line 1408 "lsys.tab.c"
    break;

  case 22: /* optional_successors: optional_successors successor  */
#line 229 "lsys.y"
                    { (yyval.successors) = (yyvsp[-1].successors);
		      (yyval.successors)->append((yyvsp[0].successor));
		    }
#line 1416 "lsys.tab.c"
    break;

  case 23: /* optional_successors: %empty  */
#line 233 "lsys.y"
                    { (yyval.successors) = new LSys::List<Successor>; }
#line 1422 "lsys.tab.c"
    break;

  case 24: /* successor: YIELDS probability modules '\n'  */
#line 237 "lsys.y"
                    { (yyval.successor) = new Successor((yyvsp[-1].moduleList), (yyvsp[-2].probability));
		      PDebug(PD_PARSER, std::cerr << "Parsed successor: " << *(yyval.successor) << std::endl);
		    }
#line 1430 "lsys.tab.c"
    break;

  case 25: /* probability: '(' value ')'  */
#line 243 "lsys.y"
                    { float f;
		      if ((yyvsp[-1].value)->value(f))
			(yyval.probability) = f;
		      else
			(yyval.probability) = 0.0;
		      delete (yyvsp[-1].value);
		    }
#line 1442 "lsys.tab.c"
    break;

  case 26: /* probability: %empty  */
#line 251 "lsys.y"
                    { (yyval.probability) = 1.0; }
#line 1448 "lsys.tab.c"
    break;

  case 27: /* $@7: %empty  */
#line 255 "lsys.y"
                    { PDebug(PD_PARSER, std::cerr << "\ttentative LHS is " << *(yyvsp[0].moduleList) << std::endl); }
#line 1454 "lsys.tab.c"
    break;

  case 28: /* predecessor: modules $@7 center_list  */
#line 257 "lsys.y"
                    {
		      PDebug(PD_PARSER,
			     std::cerr << "\tcenter,right are " << *(yyvsp[0].predecessor) << std::endl);
		      (yyval.predecessor) = (yyvsp[0].predecessor);
		      if ((yyvsp[0].predecessor)->center == NULL) {
			// Two possibilities:
			//  A
			//  A > B
			// In both cases, 'modules' is center module alone;
			//  should verify list has only one module and
			//  delete the list after removing that module.

			LSys::ListIterator<Module> mi((yyvsp[-2].moduleList));
			(yyval.predecessor)->center = mi.first();
			PDebug(PD_PARSER, std::cerr << "Predecessor (no context) is: " << *(yyval.predecessor) << std::endl);
		      } else {
			// Two possibilities:
			//  A < B
			//  A < B > C
			// In both cases, 'modules' is left context

			(yyval.predecessor)->left = (yyvsp[-2].moduleList);
			PDebug(PD_PARSER, std::cerr << "Predecessor (context) is: " << *(yyval.predecessor) << std::endl);
		      }
		    }
#line 1484 "lsys.tab.c"
    break;

  case 29: /* center_list: '<' module right_list  */
#line 285 "lsys.y"
                    { (yyval.predecessor) = new Predecessor(NULL, (yyvsp[-1].module), (yyvsp[0].moduleList)); }
#line 1490 "lsys.tab.c"
    break;

  case 30: /* center_list: right_list  */
#line 287 "lsys.y"
                    { (yyval.predecessor) = new Predecessor(NULL, NULL, (yyvsp[0].moduleList)); }
#line 1496 "lsys.tab.c"
    break;

  case 31: /* right_list: '>' modules  */
#line 291 "lsys.y"
                    { (yyval.moduleList) = (yyvsp[0].moduleList); }
#line 1502 "lsys.tab.c"
    break;

  case 32: /* right_list: %empty  */
#line 293 "lsys.y"
                    { (yyval.moduleList) = NULL; }
#line 1508 "lsys.tab.c"
    break;

  case 33: /* modules: modules module  */
#line 297 "lsys.y"
                    { (yyvsp[-1].moduleList)->append((yyvsp[0].module));
		      (yyval.moduleList) = (yyvsp[-1].moduleList);
		    }
#line 1516 "lsys.tab.c"
    break;

  case 34: /* modules: %empty  */
#line 301 "lsys.y"
                    { (yyval.moduleList) = new LSys::List<Module>; }
#line 1522 "lsys.tab.c"
    break;

  case 35: /* module: name arguments  */
#line 306 "lsys.y"
                    { Value v;
		      bool ignore = parserIgnoreTable.lookup(Name((yyvsp[-1].name)), v);

		      (yyval.module) = new Module(Name((yyvsp[-1].name)), (yyvsp[0].expressionList), ignore);
		    }
#line 1532 "lsys.tab.c"
    break;

  case 36: /* $@8: %empty  */
#line 314 "lsys.y"
                    { lex_pushstate(LEX_EXPRESSION); }
#line 1538 "lsys.tab.c"
    break;

  case 37: /* arguments: '(' $@8 exprlist ')'  */
#line 316 "lsys.y"
                    { lex_popstate();
		      (yyval.expressionList) = (yyvsp[-1].expressionList);
		    }
#line 1546 "lsys.tab.c"
    break;

  case 38: /* arguments: %empty  */
#line 320 "lsys.y"
                    { (yyval.expressionList) = NULL; }
#line 1552 "lsys.tab.c"
    break;

  case 39: /* exprlist: exprlist ',' expression  */
#line 324 "lsys.y"
                    { if (BindExpression == true) {
			Value v = (yyvsp[0].expression)->evaluate(parserSymbolTable);
			(yyvsp[-2].expressionList)->append(new Expression(v));
			delete (yyvsp[0].expression);
		      } else {
			(yyvsp[-2].expressionList)->append((yyvsp[0].expression));
		      }
		      PDebug(PD_PARSER, std::cerr << "Parsed additional expression: " << *(yyvsp[0].expression) << std::endl);
		      (yyval.expressionList) = (yyvsp[-2].expressionList);
		    }
#line 1567 "lsys.tab.c"
    break;

  case 40: /* exprlist: expression  */
#line 335 "lsys.y"
                    { (yyval.expressionList) = new LSys::List<Expression>;
		      PDebug(PD_PARSER, std::cerr << "Parsed expression: " << *(yyvsp[0].expression) << std::endl);
		      if (BindExpression == true) {
			Value v = (yyvsp[0].expression)->evaluate(parserSymbolTable);
			(yyval.expressionList)->append(new Expression(v));
			delete (yyvsp[0].expression);
		      } else {
			(yyval.expressionList)->append((yyvsp[0].expression));
		      }
		    }
#line 1582 "lsys.tab.c"
    break;

  case 41: /* exprlist: %empty  */
#line 346 "lsys.y"
                    { (yyval.expressionList) = new LSys::List<Expression>; }
#line 1588 "lsys.tab.c"
    break;

  case 42: /* $@9: %empty  */
#line 351 "lsys.y"
                    { lex_pushstate(LEX_EXPRESSION); }
#line 1594 "lsys.tab.c"
    break;

  case 43: /* optional_conditional: ':' $@9 conditional  */
#line 353 "lsys.y"
                    { lex_popstate();
		      (yyval.expression) = (yyvsp[0].expression);
		    }
#line 1602 "lsys.tab.c"
    break;

  case 44: /* optional_conditional: %empty  */
#line 357 "lsys.y"
                    { (yyval.expression) = NULL; }
#line 1608 "lsys.tab.c"
    break;

  case 45: /* conditional: '*'  */
#line 361 "lsys.y"
                    { (yyval.expression) = NULL; }
#line 1614 "lsys.tab.c"
    break;

  case 46: /* conditional: expression  */
#line 363 "lsys.y"
                    { PDebug(PD_PARSER, std::cerr << "Parsed conditional expression: " << *(yyvsp[0].expression) << std::endl);
		      (yyval.expression) = (yyvsp[0].expression); }
#line 1621 "lsys.tab.c"
    break;

  case 47: /* expression: expression OR expression  */
#line 368 "lsys.y"
                    { (yyval.expression) = new Expression(OR ,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1627 "lsys.tab.c"
    break;

  case 48: /* expression: expression AND expression  */
#line 370 "lsys.y"
                    { (yyval.expression) = new Expression(AND,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1633 "lsys.tab.c"
    break;

  case 49: /* expression: expression '|' expression  */
#line 372 "lsys.y"
                    { (yyval.expression) = new Expression('|',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1639 "lsys.tab.c"
    break;

  case 50: /* expression: expression '&' expression  */
#line 374 "lsys.y"
                    { (yyval.expression) = new Expression('&',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1645 "lsys.tab.c"
    break;

  case 51: /* expression: expression EQ expression  */
#line 376 "lsys.y"
                    { (yyval.expression) = new Expression(EQ ,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1651 "lsys.tab.c"
    break;

  case 52: /* expression: expression NE expression  */
#line 378 "lsys.y"
                    { (yyval.expression) = new Expression(NE ,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1657 "lsys.tab.c"
    break;

  case 53: /* expression: expression '<' expression  */
#line 380 "lsys.y"
                    { (yyval.expression) = new Expression('<',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1663 "lsys.tab.c"
    break;

  case 54: /* expression: expression LE expression  */
#line 382 "lsys.y"
                    { (yyval.expression) = new Expression(LE ,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1669 "lsys.tab.c"
    break;

  case 55: /* expression: expression GE expression  */
#line 384 "lsys.y"
                    { (yyval.expression) = new Expression(GE ,(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1675 "lsys.tab.c"
    break;

  case 56: /* expression: expression '>' expression  */
#line 386 "lsys.y"
                    { (yyval.expression) = new Expression('>',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1681 "lsys.tab.c"
    break;

  case 57: /* expression: expression '+' expression  */
#line 388 "lsys.y"
                    { (yyval.expression) = new Expression('+',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1687 "lsys.tab.c"
    break;

  case 58: /* expression: expression '-' expression  */
#line 390 "lsys.y"
                    { (yyval.expression) = new Expression('-',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1693 "lsys.tab.c"
    break;

  case 59: /* expression: expression '*' expression  */
#line 392 "lsys.y"
                    { (yyval.expression) = new Expression('*',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1699 "lsys.tab.c"
    break;

  case 60: /* expression: expression '/' expression  */
#line 394 "lsys.y"
                    { (yyval.expression) = new Expression('/',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1705 "lsys.tab.c"
    break;

  case 61: /* expression: expression '%' expression  */
#line 396 "lsys.y"
                    { (yyval.expression) = new Expression('%',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1711 "lsys.tab.c"
    break;

  case 62: /* expression: expression '^' expression  */
#line 398 "lsys.y"
                    { (yyval.expression) = new Expression('^',(yyvsp[-2].expression),(yyvsp[0].expression)); }
#line 1717 "lsys.tab.c"
    break;

  case 63: /* expression: '-' expression  */
#line 400 "lsys.y"
                    { (yyval.expression) = new Expression(UMINUS,(yyvsp[0].expression),(Expression *)NULL); }
#line 1723 "lsys.tab.c"
    break;

  case 64: /* expression: '!' expression  */
#line 402 "lsys.y"
                    { (yyval.expression) = new Expression('!'	,(yyvsp[0].expression),(Expression *)NULL); }
#line 1729 "lsys.tab.c"
    break;

  case 65: /* expression: '~' expression  */
#line 404 "lsys.y"
                    { (yyval.expression) = new Expression('~'	,(yyvsp[0].expression),(Expression *)NULL); }
#line 1735 "lsys.tab.c"
    break;

  case 66: /* expression: '(' expression ')'  */
#line 406 "lsys.y"
                    { (yyval.expression) = (yyvsp[-1].expression); }
#line 1741 "lsys.tab.c"
    break;

  case 67: /* expression: name arguments  */
#line 409 "lsys.y"
                    { (yyval.expression) = new Expression(Name((yyvsp[-1].name)), (yyvsp[0].expressionList)); }
#line 1747 "lsys.tab.c"
    break;

  case 68: /* expression: value  */
#line 411 "lsys.y"
                    { (yyval.expression) = new Expression(*(yyvsp[0].value)); delete (yyvsp[0].value); }
#line 1753 "lsys.tab.c"
    break;

  case 69: /* value: INTEGER  */
#line 415 "lsys.y"
                    { (yyval.value) = new Value(std::atoi(lex_token())); }
#line 1759 "lsys.tab.c"
    break;

  case 70: /* value: REAL  */
#line 417 "lsys.y"
                    { (yyval.value) = new Value(std::atof(lex_token())); }
#line 1765 "lsys.tab.c"
    break;

  case 71: /* name: NAME  */
#line 421 "lsys.y"
                    { PDebug(PD_NAME, std::cerr << "Calling Name::Name(token @" << ((void *)lex_token()) << " = " << lex_token() << ')' << std::endl);
		      (yyval.name) = Name(lex_token());
		    }
#line 1773 "lsys.tab.c"
    break;


#line 1777 "lsys.tab.c"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
      throw std::runtime_error("Syntax error");
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 425 "lsys.y"


void yyerror(char *msg) {
    std::cout << std::flush;
    std::cerr << msg << " at line " << lexline << ", column "
	 << lexcol << "\n" << std::flush;
}


#ifdef sun
// Probably should be #ifndef _USES_BISON_ or some such
#ifndef __GNUG__
// /usr/lib/yaccpar is old-C and calls to free() should cast to (int *).
// Since there's no way to do that, we overload free() instead.
// This probably applies to other System V yaccs, too.
void free(int *ip) {
    free((char *)ip);
}

void free(YYSTYPE *yp) {
    free((char *)yp);
}
#endif /*!__GNUG__*/
#endif /*sun*/

