#pragma GCC diagnostic ignored "-Wall"
#pragma GCC diagnostic ignored "-Wregister"
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wold-style-cast"
#pragma GCC diagnostic ignored "-Wextra"
#pragma GCC diagnostic ignored "-Wwrite-strings"

/* A Bison parser, made from lsys.y
   by GNU bison 1.35.  */

#define YYBISON 1  /* Identify Bison output.  */

# define	ERROR	257
# define	VALUE	258
# define	INTEGER	259
# define	REAL	260
# define	FUNCTION	261
# define	IGNORE	262
# define	INCLUDE	263
# define	DEFINE	264
# define	YIELDS	265
# define	NAME	266
# define	START	267
# define	OR	268
# define	AND	269
# define	EQ	270
# define	NE	271
# define	LE	272
# define	GE	273
# define	UMINUS	274

#line 1 "lsys.y"

/* lsys.y - parser for L-systems.
 *
 * Copyright (C) 1990, Jonathan P. Leech
 *
 * This software may be freely copied, modified, and redistributed,
 * provided that this copyright notice is preserved on all copies.
 *
 * There is no warranty or other guarantee of fitness for this software,
 * it is provided solely "as is". Bug reports or fixes may be sent
 * to the author, who may or may not act on them as he desires.
 *
 * You may not include this software in a program or other software product
 * without supplying the source, or without informing the end-user that the
 * source is available for no extra charge.
 *
 * If you modify this software, you should include a notice giving the
 * name of the person performing the modification, the date of modification,
 * and the reason for such modification.
 *
 * $Log:	lsys.y,v $
 * Revision 1.3  91/03/20  10:33:14  leech
 * Support for G++.
 *
 * Revision 1.2  90/10/12  18:48:23  leech
 * First public release.
 *
 */

#undef YYSTYPE /* stop compilation errors */

#include "parser.h"

#include "debug.h"

#include <cstdlib>
#include <ctype.h>
#include <malloc.h>

using L_SYSTEM::Expression;
using L_SYSTEM::LSysModel;
using L_SYSTEM::Module;
using L_SYSTEM::Name;
using L_SYSTEM::Predecessor;
using L_SYSTEM::Production;
using L_SYSTEM::Successor;
using L_SYSTEM::Value;

/* default version in liby:yyerror.o as extern "C" void yyerror(char *); */
void yyerror(char *);

/* lexical scanner (in lex.yy.o when automatically produced by lex) */
#include "lexdefs.h"
extern int yylex(void);

extern void lex_pushstate(int);
extern void lex_popstate(void );
extern int lexcol;
extern int lexline;

/* Return a pointer to the last string token parsed; in lexer */
extern char *lex_token(void);


// Dictionary & rule information needed/generated by the parser
LSysModel* parseInfo; // GLK

void set_parser_globals(LSysModel* m)
{
  parseInfo = m;
};


// A separate list of CF productions is maintained until all
//  productions have been read.
static L_SYSTEM::List<Production> Context_free_rules;

// Should expressions be evaluated when read in?
static bool BindExpression = false;


#line 83 "lsys.y"
#ifndef YYSTYPE
typedef union {
  int name;                         /* module or variable name id */
  float probability;                /* production probability */
  Value* value;	                    /* numeric value */
  Module* module;
  Expression* expression;
  L_SYSTEM::List<Module>* moduleList;	  /* list of modules as in a production successor */
  L_SYSTEM::List<Expression>* expressionList;	/* list of expressions within a module */
  Predecessor* predecessor;	        /* a production predecessor */
  Successor* successor;	            /* a production successor */
  L_SYSTEM::List<Successor>* successors;/* list of production successors with probabilities */
} yystype;
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
#endif
#ifndef YYDEBUG
# define YYDEBUG 0
#endif



#define	YYFINAL		116
#define	YYFLAG		-32768
#define	YYNTBASE	38

/* YYTRANSLATE(YYLEX) -- Bison token number corresponding to YYLEX. */
#define YYTRANSLATE(x) ((unsigned)(x) <= 274 ? yytranslate[x] : 68)

/* YYTRANSLATE[YYLEX] -- Bison token number corresponding to YYLEX. */
static const char yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
      33,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,    31,     2,     2,     2,    28,    17,     2,
      35,    36,    26,    24,    37,    25,     2,    27,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,    34,     2,
      20,     2,    23,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,    29,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,    16,     2,    32,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     3,     4,     5,
       6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
      18,    19,    21,    22,    30
};

#if YYDEBUG
static const short yyprhs[] =
{
       0,     0,     1,     4,     7,     8,    12,    13,    18,    19,
      25,    26,    32,    34,    35,    39,    40,    47,    50,    51,
      53,    56,    59,    60,    65,    69,    70,    71,    75,    79,
      81,    84,    85,    88,    89,    92,    93,    98,    99,   103,
     105,   106,   107,   111,   112,   114,   116,   120,   124,   128,
     132,   136,   140,   144,   148,   152,   156,   160,   164,   168,
     172,   176,   180,   183,   186,   189,   193,   196,   198,   200,
     202
};
static const short yyrhs[] =
{
      -1,    39,    40,     0,    40,    41,     0,     0,     9,    57,
      33,     0,     0,     8,    42,    47,    33,     0,     0,    10,
      67,    65,    43,    33,     0,     0,    13,    34,    44,    57,
      33,     0,    33,     0,     0,    34,    45,    65,     0,     0,
      67,    46,    34,    53,    62,    49,     0,    47,    48,     0,
       0,    67,     0,    51,    50,     0,    50,    51,     0,     0,
      11,    52,    57,    33,     0,    35,    66,    36,     0,     0,
       0,    57,    54,    55,     0,    20,    58,    56,     0,    56,
       0,    23,    57,     0,     0,    57,    58,     0,     0,    67,
      59,     0,     0,    35,    60,    61,    36,     0,     0,    61,
      37,    65,     0,    65,     0,     0,     0,    34,    63,    64,
       0,     0,    26,     0,    65,     0,    65,    14,    65,     0,
      65,    15,    65,     0,    65,    16,    65,     0,    65,    17,
      65,     0,    65,    18,    65,     0,    65,    19,    65,     0,
      65,    20,    65,     0,    65,    21,    65,     0,    65,    22,
      65,     0,    65,    23,    65,     0,    65,    24,    65,     0,
      65,    25,    65,     0,    65,    26,    65,     0,    65,    27,
      65,     0,    65,    28,    65,     0,    65,    29,    65,     0,
      25,    65,     0,    31,    65,     0,    32,    65,     0,    35,
      65,    36,     0,    67,    59,     0,    66,     0,     5,     0,
       6,     0,    12,     0
};

#endif

#if YYDEBUG
/* YYRLINE[YYN] -- source line where rule number YYN was defined. */
static const short yyrline[] =
{
       0,   124,   124,   137,   138,   141,   144,   144,   150,   150,
     159,   159,   171,   174,   174,   184,   184,   202,   203,   206,
     217,   226,   231,   235,   241,   249,   253,   253,   283,   285,
     289,   291,   295,   299,   303,   312,   312,   318,   322,   333,
     344,   348,   348,   355,   359,   361,   366,   368,   370,   372,
     374,   376,   378,   380,   382,   384,   386,   388,   390,   392,
     394,   396,   398,   400,   402,   404,   406,   409,   413,   415,
     419
};
#endif


#if (YYDEBUG) || defined YYERROR_VERBOSE

/* YYTNAME[TOKEN_NUM] -- String name of the token TOKEN_NUM. */
static const char *const yytname[] =
{
  "$", "error", "$undefined.", "ERROR", "VALUE", "INTEGER", "REAL",
  "FUNCTION", "IGNORE", "INCLUDE", "DEFINE", "YIELDS", "NAME", "START",
  "OR", "AND", "'|'", "'&'", "EQ", "NE", "'<'", "LE", "GE", "'>'", "'+'",
  "'-'", "'*'", "'/'", "'%'", "'^'", "UMINUS", "'!'", "'~'", "'\\n'",
  "':'", "'('", "')'", "','", "lsystem", "@1", "lines", "line", "@2",
  "@3", "@4", "@5", "@6", "names", "single_name", "successors",
  "optional_successors", "successor", "probability", "predecessor", "@7",
  "center_list", "right_list", "modules", "module", "arguments", "@8",
  "exprlist", "optional_conditional", "@9", "conditional", "expression",
  "value", "name", 0
};
#endif

/* YYR1[YYN] -- Symbol number of symbol that rule YYN derives. */
static const short yyr1[] =
{
       0,    39,    38,    40,    40,    41,    42,    41,    43,    41,
      44,    41,    41,    45,    41,    46,    41,    47,    47,    48,
      49,    50,    50,    51,    52,    52,    54,    53,    55,    55,
      56,    56,    57,    57,    58,    60,    59,    59,    61,    61,
      61,    63,    62,    62,    64,    64,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    65,    65,
      65,    65,    65,    65,    65,    65,    65,    65,    66,    66,
      67
};

/* YYR2[YYN] -- Number of symbols composing right hand side of rule YYN. */
static const short yyr2[] =
{
       0,     0,     2,     2,     0,     3,     0,     4,     0,     5,
       0,     5,     1,     0,     3,     0,     6,     2,     0,     1,
       2,     2,     0,     4,     3,     0,     0,     3,     3,     1,
       2,     0,     2,     0,     2,     0,     4,     0,     3,     1,
       0,     0,     3,     0,     1,     1,     3,     3,     3,     3,
       3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
       3,     3,     2,     2,     2,     3,     2,     1,     1,     1,
       1
};

/* YYDEFACT[S] -- default rule to reduce with in state S when YYTABLE
   doesn't specify something else to do.  Zero means the default is an
   error. */
static const short yydefact[] =
{
       1,     4,     2,     6,    33,     0,    70,     0,    12,    13,
       3,    15,    18,     0,     0,    10,     0,     0,     0,     5,
      32,    37,    68,    69,     0,     0,     0,     0,     8,    67,
      37,    33,    14,    33,     7,    17,    19,    35,    34,    62,
      63,    64,     0,     0,     0,     0,     0,     0,     0,     0,
       0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
      66,     0,    43,    26,    40,    65,    46,    47,    48,    49,
      50,    51,    52,    53,    54,    55,    56,    57,    58,    59,
      60,    61,     9,    11,    41,     0,    31,     0,    39,     0,
      25,    16,    22,     0,    33,    27,    29,    36,     0,    44,
      42,    45,     0,    33,    20,    31,    30,    38,     0,     0,
      21,    28,    24,    23,     0,     0,     0
};

static const short yydefgoto[] =
{
     114,     1,     2,    10,    12,    59,    31,    16,    17,    18,
      35,    91,   104,    92,   103,    62,    86,    95,    96,    13,
      20,    38,    64,    87,    85,    89,   100,    28,    29,    30
};

static const short yypact[] =
{
  -32768,-32768,    14,-32768,-32768,   -11,-32768,   -24,-32768,-32768,
  -32768,-32768,-32768,    -5,    50,-32768,    50,   -13,    -3,-32768,
  -32768,   -10,-32768,-32768,    50,    50,    50,    50,   117,-32768,
     -10,-32768,   117,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
  -32768,-32768,    94,    50,    50,    50,    50,    50,    50,    50,
      50,    50,    50,    50,    50,    50,    50,    50,    50,    18,
  -32768,    17,    42,   -11,    50,-32768,   132,   146,   159,    74,
     169,   169,    39,    39,    39,    39,    -9,    -9,    55,    55,
      55,-32768,-32768,-32768,-32768,    76,   -18,    21,   117,    48,
      53,-32768,-32768,   -11,-32768,-32768,-32768,-32768,    50,-32768,
  -32768,   117,    66,-32768,    76,    67,   -11,   117,    69,    37,
  -32768,-32768,-32768,-32768,    89,   106,-32768
};

static const short yypgoto[] =
{
  -32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
  -32768,-32768,-32768,    20,-32768,-32768,-32768,-32768,    22,   -25,
      32,    96,-32768,-32768,-32768,-32768,-32768,   -12,    26,    -2
};


#define	YYLAST		198


static const short yytable[] =
{
      11,     6,    93,    14,    32,    94,    61,     6,    63,     6,
      15,    21,    39,    40,    41,    42,    36,    55,    56,    57,
      58,    33,     3,     4,     5,    37,     6,     7,    19,     6,
      34,    66,    67,    68,    69,    70,    71,    72,    73,    74,
      75,    76,    77,    78,    79,    80,    81,     8,     9,     6,
      83,    82,    88,    22,    23,    22,    23,    97,    98,    21,
       6,    21,     6,    53,    54,    55,    56,    57,    58,   106,
     113,    22,    23,    24,    99,    24,    84,   101,   109,    25,
      26,    25,    26,    27,    58,    27,   107,    90,   102,   115,
      94,    21,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,    21,   112,   116,    21,    43,    44,
      45,    46,    47,    48,    49,    50,    51,    52,    53,    54,
      55,    56,    57,    58,   110,   105,    60,   111,   108,     0,
      65,    43,    44,    45,    46,    47,    48,    49,    50,    51,
      52,    53,    54,    55,    56,    57,    58,    44,    45,    46,
      47,    48,    49,    50,    51,    52,    53,    54,    55,    56,
      57,    58,    45,    46,    47,    48,    49,    50,    51,    52,
      53,    54,    55,    56,    57,    58,    46,    47,    48,    49,
      50,    51,    52,    53,    54,    55,    56,    57,    58,    49,
      50,    51,    52,    53,    54,    55,    56,    57,    58
};

static const short yycheck[] =
{
       2,    12,    20,     5,    16,    23,    31,    12,    33,    12,
      34,    13,    24,    25,    26,    27,    18,    26,    27,    28,
      29,    34,     8,     9,    10,    35,    12,    13,    33,    12,
      33,    43,    44,    45,    46,    47,    48,    49,    50,    51,
      52,    53,    54,    55,    56,    57,    58,    33,    34,    12,
      33,    33,    64,     5,     6,     5,     6,    36,    37,    61,
      12,    63,    12,    24,    25,    26,    27,    28,    29,    94,
      33,     5,     6,    25,    26,    25,    34,    89,   103,    31,
      32,    31,    32,    35,    29,    35,    98,    11,    35,     0,
      23,    93,    18,    19,    20,    21,    22,    23,    24,    25,
      26,    27,    28,    29,   106,    36,     0,   109,    14,    15,
      16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
      26,    27,    28,    29,   104,    93,    30,   105,   102,    -1,
      36,    14,    15,    16,    17,    18,    19,    20,    21,    22,
      23,    24,    25,    26,    27,    28,    29,    15,    16,    17,
      18,    19,    20,    21,    22,    23,    24,    25,    26,    27,
      28,    29,    16,    17,    18,    19,    20,    21,    22,    23,
      24,    25,    26,    27,    28,    29,    17,    18,    19,    20,
      21,    22,    23,    24,    25,    26,    27,    28,    29,    20,
      21,    22,    23,    24,    25,    26,    27,    28,    29
};
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
#line 3 "F:\\program files\\bison/share/bison/bison.simple"

/* Skeleton output parser for bison,

   Copyright (C) 1984, 1989, 1990, 2000, 2001, 2002 Free Software
   Foundation, Inc.

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 59 Temple Place - Suite 330,
   Boston, MA 02111-1307, USA.  */

/* As a special exception, when this file is copied by Bison into a
   Bison output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison.  */

/* This is the parser code that is written into each bison parser when
   the %semantic_parser declaration is not specified in the grammar.
   It was written by Richard Stallman by simplifying the hairy parser
   used when %semantic_parser is specified.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

#if ! defined (yyoverflow) || defined (YYERROR_VERBOSE)

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# if YYSTACK_USE_ALLOCA
#  define YYSTACK_ALLOC alloca
# else
#  ifndef YYSTACK_USE_ALLOCA
#   if defined (alloca) || defined (_ALLOCA_H)
#    define YYSTACK_ALLOC alloca
#   else
#    ifdef __GNUC__
#     define YYSTACK_ALLOC __builtin_alloca
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's `empty if-body' warning. */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
# else
#  if defined (__STDC__) || defined (__cplusplus)
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   define YYSIZE_T size_t
#  endif
#  define YYSTACK_ALLOC malloc
#  define YYSTACK_FREE free
# endif
#endif /* ! defined (yyoverflow) || defined (YYERROR_VERBOSE) */


#if (! defined (yyoverflow) \
     && (! defined (__cplusplus) \
	 || (YYLTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  short yyss;
  YYSTYPE yyvs;
# if YYLSP_NEEDED
  YYLTYPE yyls;
# endif
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAX (sizeof (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# if YYLSP_NEEDED
#  define YYSTACK_BYTES(N) \
     ((N) * (sizeof (short) + sizeof (YYSTYPE) + sizeof (YYLTYPE))	\
      + 2 * YYSTACK_GAP_MAX)
# else
#  define YYSTACK_BYTES(N) \
     ((N) * (sizeof (short) + sizeof (YYSTYPE))				\
      + YYSTACK_GAP_MAX)
# endif

/* Copy COUNT objects from FROM to TO.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if 1 < __GNUC__
#   define YYCOPY(To, From, Count) \
      __builtin_memcpy (To, From, (Count) * sizeof (*(From)))
#  else
#   define YYCOPY(To, From, Count)		\
      do					\
	{					\
	  register YYSIZE_T yyi;		\
	  for (yyi = 0; yyi < (Count); yyi++)	\
	    (To)[yyi] = (From)[yyi];		\
	}					\
      while (0)
#  endif
# endif

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack)					\
    do									\
      {									\
	YYSIZE_T yynewbytes;						\
	YYCOPY (&yyptr->Stack, Stack, yysize);				\
	Stack = &yyptr->Stack;						\
	yynewbytes = yystacksize * sizeof (*Stack) + YYSTACK_GAP_MAX;	\
	yyptr += yynewbytes / sizeof (*yyptr);				\
      }									\
    while (0)

#endif


#if ! defined (YYSIZE_T) && defined (__SIZE_TYPE__)
# define YYSIZE_T __SIZE_TYPE__
#endif
#if ! defined (YYSIZE_T) && defined (size_t)
# define YYSIZE_T size_t
#endif
#if ! defined (YYSIZE_T)
# if defined (__STDC__) || defined (__cplusplus)
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# endif
#endif
#if ! defined (YYSIZE_T)
# define YYSIZE_T unsigned int
#endif

#define yyerrok		(yyerrstatus = 0)
#define yyclearin	(yychar = YYEMPTY)
#define YYEMPTY		-2
#define YYEOF		0
#define YYACCEPT	goto yyacceptlab
#define YYABORT 	goto yyabortlab
#define YYERROR		goto yyerrlab1
/* Like YYERROR except do call yyerror.  This remains here temporarily
   to ease the transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL		goto yyerrlab
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(Token, Value)					\
do								\
  if (yychar == YYEMPTY && yylen == 1)				\
    {								\
      yychar = (Token);						\
      yylval = (Value);						\
      yychar1 = YYTRANSLATE (yychar);				\
      YYPOPSTACK;						\
      goto yybackup;						\
    }								\
  else								\
    { 								\
      yyerror ("syntax error: cannot back up");			\
      YYERROR;							\
    }								\
while (0)

#define YYTERROR	1
#define YYERRCODE	256


/* YYLLOC_DEFAULT -- Compute the default location (before the actions
   are run).

   When YYLLOC_DEFAULT is run, CURRENT is set the location of the
   first token.  By default, to implement support for ranges, extend
   its range to the last symbol.  */

#ifndef YYLLOC_DEFAULT
# define YYLLOC_DEFAULT(Current, Rhs, N)       	\
   Current.last_line   = Rhs[N].last_line;	\
   Current.last_column = Rhs[N].last_column;
#endif


/* YYLEX -- calling `yylex' with the right arguments.  */

#if YYPURE
# if YYLSP_NEEDED
#  ifdef YYLEX_PARAM
#   define YYLEX		yylex (&yylval, &yylloc, YYLEX_PARAM)
#  else
#   define YYLEX		yylex (&yylval, &yylloc)
#  endif
# else /* !YYLSP_NEEDED */
#  ifdef YYLEX_PARAM
#   define YYLEX		yylex (&yylval, YYLEX_PARAM)
#  else
#   define YYLEX		yylex (&yylval)
#  endif
# endif /* !YYLSP_NEEDED */
#else /* !YYPURE */
# define YYLEX			yylex ()
#endif /* !YYPURE */


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)			\
do {						\
  if (yydebug)					\
    YYFPRINTF Args;				\
} while (0)
/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args)
#endif /* !YYDEBUG */

/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef	YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   SIZE_MAX < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#if YYMAXDEPTH == 0
# undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif

#ifdef YYERROR_VERBOSE

# ifndef yystrlen
#  if defined (__GLIBC__) && defined (_STRING_H)
#   define yystrlen strlen
#  else
/* Return the length of YYSTR.  */
static YYSIZE_T
#   if defined (__STDC__) || defined (__cplusplus)
yystrlen (const char *yystr)
#   else
yystrlen (yystr)
     const char *yystr;
#   endif
{
  register const char *yys = yystr;

  while (*yys++ != '\0')
    continue;

  return yys - yystr - 1;
}
#  endif
# endif

# ifndef yystpcpy
#  if defined (__GLIBC__) && defined (_STRING_H) && defined (_GNU_SOURCE)
#   define yystpcpy stpcpy
#  else
/* Copy YYSRC to YYDEST, returning the address of the terminating '\0' in
   YYDEST.  */
static char *
#   if defined (__STDC__) || defined (__cplusplus)
yystpcpy (char *yydest, const char *yysrc)
#   else
yystpcpy (yydest, yysrc)
     char *yydest;
     const char *yysrc;
#   endif
{
  register char *yyd = yydest;
  register const char *yys = yysrc;

  while ((*yyd++ = *yys++) != '\0')
    continue;

  return yyd - 1;
}
#  endif
# endif
#endif

#line 315 "F:\\program files\\bison/share/bison/bison.simple"


/* The user can define YYPARSE_PARAM as the name of an argument to be passed
   into yyparse.  The argument should have type void *.
   It should actually point to an object.
   Grammar actions can access the variable by casting it
   to the proper pointer type.  */

#ifdef YYPARSE_PARAM
# if defined (__STDC__) || defined (__cplusplus)
#  define YYPARSE_PARAM_ARG void *YYPARSE_PARAM
#  define YYPARSE_PARAM_DECL
# else
#  define YYPARSE_PARAM_ARG YYPARSE_PARAM
#  define YYPARSE_PARAM_DECL void *YYPARSE_PARAM;
# endif
#else /* !YYPARSE_PARAM */
# define YYPARSE_PARAM_ARG
# define YYPARSE_PARAM_DECL
#endif /* !YYPARSE_PARAM */

/* Prevent warning if -Wstrict-prototypes.  */
#ifdef __GNUC__
# ifdef YYPARSE_PARAM
int yyparse (void *);
# else
int yyparse (void);
# endif
#endif

/* YY_DECL_VARIABLES -- depending whether we use a pure parser,
   variables are global, or local to YYPARSE.  */

#define YY_DECL_NON_LSP_VARIABLES			\
/* The lookahead symbol.  */				\
int yychar;						\
							\
/* The semantic value of the lookahead symbol. */	\
YYSTYPE yylval;						\
							\
/* Number of parse errors so far.  */			\
int yynerrs;

#if YYLSP_NEEDED
# define YY_DECL_VARIABLES			\
YY_DECL_NON_LSP_VARIABLES			\
						\
/* GetPosition data for the lookahead symbol.  */	\
YYLTYPE yylloc;
#else
# define YY_DECL_VARIABLES			\
YY_DECL_NON_LSP_VARIABLES
#endif


/* If nonreentrant, generate the variables here. */

#if !YYPURE
YY_DECL_VARIABLES
#endif  /* !YYPURE */

int
yyparse (YYPARSE_PARAM_ARG)
     YYPARSE_PARAM_DECL
{
  /* If reentrant, generate the variables here. */
#if YYPURE
  YY_DECL_VARIABLES
#endif  /* !YYPURE */

  register int yystate;
  register int yyn;
  int yyresult;
  /* Number of tokens to shift before error messages enabled.  */
  int yyerrstatus;
  /* Lookahead token as an internal (translated) token number.  */
  int yychar1 = 0;

  /* Three stacks and their tools:
     `yyss': related to states,
     `yyvs': related to semantic values,
     `yyls': related to locations.

     Refer to the stacks thru separate pointers, to allow yyoverflow
     to reallocate them elsewhere.  */

  /* The state stack. */
  short	yyssa[YYINITDEPTH];
  short *yyss = yyssa;
  register short *yyssp;

  /* The semantic value stack.  */
  YYSTYPE yyvsa[YYINITDEPTH];
  YYSTYPE *yyvs = yyvsa;
  register YYSTYPE *yyvsp;

#if YYLSP_NEEDED
  /* The location stack.  */
  YYLTYPE yylsa[YYINITDEPTH];
  YYLTYPE *yyls = yylsa;
  YYLTYPE *yylsp;
#endif

#if YYLSP_NEEDED
# define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
# define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  YYSIZE_T yystacksize = YYINITDEPTH;


  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;
#if YYLSP_NEEDED
  YYLTYPE yyloc;
#endif

  /* When reducing, the number of symbols on the RHS of the reduced
     rule. */
  int yylen;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yystate = 0;
  yyerrstatus = 0;
  yynerrs = 0;
  yychar = YYEMPTY;		/* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss;
  yyvsp = yyvs;
#if YYLSP_NEEDED
  yylsp = yyls;
#endif
  goto yysetstate;

/*------------------------------------------------------------.
| yynewstate -- Push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
 yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed. so pushing a state here evens the stacks.
     */
  yyssp++;

 yysetstate:
  *yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYSIZE_T yysize = yyssp - yyss + 1;

#ifdef yyoverflow
      {
	/* Give user a chance to reallocate the stack. Use copies of
	   these so that the &'s don't force the real ones into
	   memory.  */
	YYSTYPE *yyvs1 = yyvs;
	short *yyss1 = yyss;

	/* Each stack pointer address is followed by the size of the
	   data in use in that stack, in bytes.  */
# if YYLSP_NEEDED
	YYLTYPE *yyls1 = yyls;
	/* This used to be a conditional around just the two extra args,
	   but that might be undefined if yyoverflow is a macro.  */
	yyoverflow ("parser stack overflow",
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yyls1, yysize * sizeof (*yylsp),
		    &yystacksize);
	yyls = yyls1;
# else
	yyoverflow ("parser stack overflow",
		    &yyss1, yysize * sizeof (*yyssp),
		    &yyvs1, yysize * sizeof (*yyvsp),
		    &yystacksize);
# endif
	yyss = yyss1;
	yyvs = yyvs1;
      }
#else /* no yyoverflow */
# ifndef YYSTACK_RELOCATE
      goto yyoverflowlab;
# else
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	goto yyoverflowlab;
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;

      {
	short *yyss1 = yyss;
	union yyalloc *yyptr =
	  (union yyalloc *) YYSTACK_ALLOC (YYSTACK_BYTES (yystacksize));
	if (! yyptr)
	  goto yyoverflowlab;
	YYSTACK_RELOCATE (yyss);
	YYSTACK_RELOCATE (yyvs);
# if YYLSP_NEEDED
	YYSTACK_RELOCATE (yyls);
# endif
# undef YYSTACK_RELOCATE
	if (yyss1 != yyssa)
	  YYSTACK_FREE (yyss1);
      }
# endif
#endif /* no yyoverflow */

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;
#if YYLSP_NEEDED
      yylsp = yyls + yysize - 1;
#endif

      YYDPRINTF ((stderr, "Stack size increased to %lu\n",
		  (unsigned long int) yystacksize));

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

  YYDPRINTF ((stderr, "Entering state %d\n", yystate));

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* yyresume: */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token: "));
      yychar = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (yychar <= 0)		/* This means end of input. */
    {
      yychar1 = 0;
      yychar = YYEOF;		/* Don't call YYLEX any more */

      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else
    {
      yychar1 = YYTRANSLATE (yychar);

#if YYDEBUG
     /* We have to keep this `#if YYDEBUG', since we use variables
	which are defined only if `YYDEBUG' is set.  */
      if (yydebug)
	{
	  YYFPRINTF (stderr, "Next token is %d (%s",
		     yychar, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise
	     meaning of a token, for further debugging info.  */
# ifdef YYPRINT
	  YYPRINT (stderr, yychar, yylval);
# endif
	  YYFPRINTF (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    goto yydefault;

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most NEGATIVE number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrlab;

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */
  YYDPRINTF ((stderr, "Shifting token %d (%s), ",
	      yychar, yytname[yychar1]));

  /* Discard the token being shifted unless it is eof.  */
  if (yychar != YYEOF)
    yychar = YYEMPTY;

  *++yyvsp = yylval;
#if YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  yystate = yyn;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- Do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     `$$ = $1'.

     Otherwise, the following line sets YYVAL to the semantic value of
     the lookahead token.  This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];

#if YYLSP_NEEDED
  /* Similarly for the default location.  Let the user run additional
     commands if for instance locations are ranges.  */
  yyloc = yylsp[1-yylen];
  YYLLOC_DEFAULT (yyloc, (yylsp - yylen), yylen);
#endif

#if YYDEBUG
  /* We have to keep this `#if YYDEBUG', since we use variables which
     are defined only if `YYDEBUG' is set.  */
  if (yydebug)
    {
      int yyi;

      YYFPRINTF (stderr, "Reducing via rule %d (line %d), ",
		 yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (yyi = yyprhs[yyn]; yyrhs[yyi] > 0; yyi++)
	YYFPRINTF (stderr, "%s ", yytname[yyrhs[yyi]]);
      YYFPRINTF (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif

  switch (yyn) {

case 1:
#line 125 "lsys.y"
{
		      // Get lex into correct start condition
		      lex_pushstate(LEX_EXPRESSION);
		    ;
    break;}
case 2:
#line 130 "lsys.y"
{ // This ensures that CF productions are applied last,
		      //  since they are at the end of the list of productions.
		      parserRules.append(&Context_free_rules);
		      lex_popstate();
		    ;
    break;}
case 6:
#line 145 "lsys.y"
{ lex_pushstate(LEX_MODULE); ;
    break;}
case 7:
#line 147 "lsys.y"
{ lex_popstate(); ;
    break;}
case 8:
#line 151 "lsys.y"
{ Value v;
                      if (!parserSymbolTable.Lookup(Name{yyvsp[-1].name}.str(), v))
                        parserSymbolTable.Enter(Name{yyvsp[-1].name}.str(),
                                                yyvsp[0].expression->Evaluate(parserSymbolTable));
		      delete yyvsp[0].expression;
		    ;
    break;}
case 10:
#line 160 "lsys.y"
{ lex_pushstate(LEX_MODULE);
		      // Bind starting list expressions according to symtab
		      BindExpression = true;
		    ;
    break;}
case 11:
#line 165 "lsys.y"
{ BindExpression = false;
		      lex_popstate();
		      parserStart.reset(yyvsp[-1].moduleList);
		    ;
    break;}
case 13:
#line 175 "lsys.y"
{ lex_pushstate(LEX_EXPRESSION); ;
    break;}
case 14:
#line 177 "lsys.y"
{ lex_popstate();
//		      std::cerr << "Evaluating expression: " << *yyvsp[0].expression << std::endl;
//		      std::cerr << yyvsp[0].expression->evaluate(parserSymbolTable) << std::endl;
		      delete yyvsp[0].expression;
		    ;
    break;}
case 15:
#line 185 "lsys.y"
{ lex_pushstate(LEX_MODULE); ;
    break;}
case 16:
#line 189 "lsys.y"
{ lex_popstate();
		      Production *p = new Production(Name{yyvsp[-5].name}, yyvsp[-2].predecessor, yyvsp[-1].expression, yyvsp[0].successors);
		      PDebug(PD_PARSER, std::cerr << "Parsed production: " << *p << std::endl);
		      if (p->IsContextFree())
			Context_free_rules.append(p);
		      else
			parserRules.append(p);
		    ;
    break;}
case 19:
#line 207 "lsys.y"
{
		      PDebug(PD_PARSER, std::cerr << "Ignoring GetName " << Name{yyvsp[0].name} << std::endl);
          parserIgnoreTable.Enter(Name{yyvsp[0].name}.str(), Value(1));
		    ;
    break;}
case 20:
#line 219 "lsys.y"
{ yyval.successors = new L_SYSTEM::List<Successor>;
		      yyval.successors->append(yyvsp[-1].successor);
		      yyval.successors->append(yyvsp[0].successors);
		      delete yyvsp[0].successors;
		    ;
    break;}
case 21:
#line 228 "lsys.y"
{ yyval.successors = yyvsp[-1].successors;
		      yyval.successors->append(yyvsp[0].successor);
		    ;
    break;}
case 22:
#line 232 "lsys.y"
{ yyval.successors = new L_SYSTEM::List<Successor>; ;
    break;}
case 23:
#line 236 "lsys.y"
{ yyval.successor = new Successor(yyvsp[-1].moduleList, yyvsp[-2].probability);
		      PDebug(PD_PARSER, std::cerr << "Parsed successor: " << *yyval.successor << std::endl);
		    ;
    break;}
case 24:
#line 242 "lsys.y"
{ float f;
		      if (yyvsp[-1].value->GetFloatValue(f))
			yyval.probability = f;
		      else
			yyval.probability = 0.0;
		      delete yyvsp[-1].value;
		    ;
    break;}
case 25:
#line 250 "lsys.y"
{ yyval.probability = 1.0; ;
    break;}
case 26:
#line 254 "lsys.y"
{ PDebug(PD_PARSER, std::cerr << "\ttentative LHS is " << *yyvsp[0].moduleList << std::endl); ;
    break;}
case 27:
#line 256 "lsys.y"
{
		      PDebug(PD_PARSER,
			     std::cerr << "\tcenter,right are " << *yyvsp[0].predecessor << std::endl);
		      yyval.predecessor = yyvsp[0].predecessor;
		      if (yyvsp[0].predecessor->center == NULL) {
			// Two possibilities:
			//  A
			//  A > B
			// In both cases, 'modules' is center module alone;
			//  should verify list has only one module and
			//  delete the list after removing that module.

      L_SYSTEM::ListIterator<Module> mi(yyvsp[-2].moduleList);
			yyval.predecessor->center = mi.first();
			PDebug(PD_PARSER, std::cerr << "Predecessor (no context) is: " << *yyval.predecessor << std::endl);
		      } else {
			// Two possibilities:
			//  A < B
			//  A < B > C
			// In both cases, 'modules' is left context

			yyval.predecessor->left = yyvsp[-2].moduleList;
			PDebug(PD_PARSER, std::cerr << "Predecessor (context) is: " << *yyval.predecessor << std::endl);
		      }
		    ;
    break;}
case 28:
#line 284 "lsys.y"
{ yyval.predecessor = new Predecessor(NULL, yyvsp[-1].module, yyvsp[0].moduleList); ;
    break;}
case 29:
#line 286 "lsys.y"
{ yyval.predecessor = new Predecessor(NULL, NULL, yyvsp[0].moduleList); ;
    break;}
case 30:
#line 290 "lsys.y"
{ yyval.moduleList = yyvsp[0].moduleList; ;
    break;}
case 31:
#line 292 "lsys.y"
{ yyval.moduleList = NULL; ;
    break;}
case 32:
#line 296 "lsys.y"
{ yyvsp[-1].moduleList->append(yyvsp[0].module);
		      yyval.moduleList = yyvsp[-1].moduleList;
		    ;
    break;}
case 33:
#line 300 "lsys.y"
{ yyval.moduleList = new L_SYSTEM::List<Module>; ;
    break;}
case 34:
#line 305 "lsys.y"
{ Value v;
		      bool ignore = parserIgnoreTable.Lookup(Name{yyvsp[-1].name}.str(), v);

		      yyval.module = new Module(Name{yyvsp[-1].name}, yyvsp[0].expressionList, ignore);
		    ;
    break;}
case 35:
#line 313 "lsys.y"
{ lex_pushstate(LEX_EXPRESSION); ;
    break;}
case 36:
#line 315 "lsys.y"
{ lex_popstate();
		      yyval.expressionList = yyvsp[-1].expressionList;
		    ;
    break;}
case 37:
#line 319 "lsys.y"
{ yyval.expressionList = NULL; ;
    break;}
case 38:
#line 323 "lsys.y"
{ if (BindExpression == true) {
			Value v = yyvsp[0].expression->Evaluate(parserSymbolTable);
			yyvsp[-2].expressionList->append(new Expression(v));
			delete yyvsp[0].expression;
		      } else {
			yyvsp[-2].expressionList->append(yyvsp[0].expression);
		      }
		      PDebug(PD_PARSER, std::cerr << "Parsed additional expression: " << *yyvsp[0].expression << std::endl);
		      yyval.expressionList = yyvsp[-2].expressionList;
		    ;
    break;}
case 39:
#line 334 "lsys.y"
{ yyval.expressionList = new L_SYSTEM::List<Expression>;
		      PDebug(PD_PARSER, std::cerr << "Parsed expression: " << *yyvsp[0].expression << std::endl);
		      if (BindExpression == true) {
			Value v = yyvsp[0].expression->Evaluate(parserSymbolTable);
			yyval.expressionList->append(new Expression(v));
			delete yyvsp[0].expression;
		      } else {
			yyval.expressionList->append(yyvsp[0].expression);
		      }
		    ;
    break;}
case 40:
#line 345 "lsys.y"
{ yyval.expressionList = new L_SYSTEM::List<Expression>; ;
    break;}
case 41:
#line 350 "lsys.y"
{ lex_pushstate(LEX_EXPRESSION); ;
    break;}
case 42:
#line 352 "lsys.y"
{ lex_popstate();
		      yyval.expression = yyvsp[0].expression;
		    ;
    break;}
case 43:
#line 356 "lsys.y"
{ yyval.expression = NULL; ;
    break;}
case 44:
#line 360 "lsys.y"
{ yyval.expression = NULL; ;
    break;}
case 45:
#line 362 "lsys.y"
{ PDebug(PD_PARSER, std::cerr << "Parsed conditional expression: " << *yyvsp[0].expression << std::endl);
		      yyval.expression = yyvsp[0].expression; ;
    break;}
case 46:
#line 367 "lsys.y"
{ yyval.expression = new Expression(OR ,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 47:
#line 369 "lsys.y"
{ yyval.expression = new Expression(AND,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 48:
#line 371 "lsys.y"
{ yyval.expression = new Expression('|',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 49:
#line 373 "lsys.y"
{ yyval.expression = new Expression('&',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 50:
#line 375 "lsys.y"
{ yyval.expression = new Expression(EQ ,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 51:
#line 377 "lsys.y"
{ yyval.expression = new Expression(NE ,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 52:
#line 379 "lsys.y"
{ yyval.expression = new Expression('<',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 53:
#line 381 "lsys.y"
{ yyval.expression = new Expression(LE ,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 54:
#line 383 "lsys.y"
{ yyval.expression = new Expression(GE ,yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 55:
#line 385 "lsys.y"
{ yyval.expression = new Expression('>',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 56:
#line 387 "lsys.y"
{ yyval.expression = new Expression('+',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 57:
#line 389 "lsys.y"
{ yyval.expression = new Expression('-',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 58:
#line 391 "lsys.y"
{ yyval.expression = new Expression('*',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 59:
#line 393 "lsys.y"
{ yyval.expression = new Expression('/',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 60:
#line 395 "lsys.y"
{ yyval.expression = new Expression('%',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 61:
#line 397 "lsys.y"
{ yyval.expression = new Expression('^',yyvsp[-2].expression,yyvsp[0].expression); ;
    break;}
case 62:
#line 399 "lsys.y"
{ yyval.expression = new Expression(UMINUS,yyvsp[0].expression,(Expression *)NULL); ;
    break;}
case 63:
#line 401 "lsys.y"
{ yyval.expression = new Expression('!'	,yyvsp[0].expression,(Expression *)NULL); ;
    break;}
case 64:
#line 403 "lsys.y"
{ yyval.expression = new Expression('~'	,yyvsp[0].expression,(Expression *)NULL); ;
    break;}
case 65:
#line 405 "lsys.y"
{ yyval.expression = yyvsp[-1].expression; ;
    break;}
case 66:
#line 408 "lsys.y"
{ yyval.expression = new Expression(Name{yyvsp[-1].name}, yyvsp[0].expressionList); ;
    break;}
case 67:
#line 410 "lsys.y"
{ yyval.expression = new Expression(*yyvsp[0].value); delete yyvsp[0].value; ;
    break;}
case 68:
#line 414 "lsys.y"
{ yyval.value = new Value(std::atoi(lex_token())); ;
    break;}
case 69:
#line 416 "lsys.y"
{ yyval.value = new Value(std::atof(lex_token())); ;
    break;}
case 70:
#line 420 "lsys.y"
{ PDebug(PD_NAME, std::cerr << "Calling Name::Name(token @" << ((void *)lex_token()) << " = " << lex_token() << ')' << std::endl);
		      yyval.name = Name{lex_token()}.id();
		    ;
    break;}
}

#line 705 "F:\\program files\\bison/share/bison/bison.simple"


  yyvsp -= yylen;
  yyssp -= yylen;
#if YYLSP_NEEDED
  yylsp -= yylen;
#endif

#if YYDEBUG
  if (yydebug)
    {
      short *yyssp1 = yyss - 1;
      YYFPRINTF (stderr, "state stack now");
      while (yyssp1 != yyssp)
	YYFPRINTF (stderr, " %d", *++yyssp1);
      YYFPRINTF (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;
#if YYLSP_NEEDED
  *++yylsp = yyloc;
#endif

  /* Now `shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  goto yynewstate;


/*------------------------------------.
| yyerrlab -- here on detecting error |
`------------------------------------*/
yyerrlab:
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;

#ifdef YYERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  YYSIZE_T yysize = 0;
	  char *yymsg;
	  int yyx, yycount;

	  yycount = 0;
	  /* Start YYX at -YYN if NEGATIVE to avoid NEGATIVE indexes in
	     YYCHECK.  */
	  for (yyx = yyn < 0 ? -yyn : 0;
	       yyx < (int) (sizeof (yytname) / sizeof (char *)); yyx++)
	    if (yycheck[yyx + yyn] == yyx)
	      yysize += yystrlen (yytname[yyx]) + 15, yycount++;
	  yysize += yystrlen ("parse error, unexpected ") + 1;
	  yysize += yystrlen (yytname[YYTRANSLATE (yychar)]);
	  yymsg = (char *) YYSTACK_ALLOC (yysize);
	  if (yymsg != 0)
	    {
	      char *yyp = yystpcpy (yymsg, "parse error, unexpected ");
	      yyp = yystpcpy (yyp, yytname[YYTRANSLATE (yychar)]);

	      if (yycount < 5)
		{
		  yycount = 0;
		  for (yyx = yyn < 0 ? -yyn : 0;
		       yyx < (int) (sizeof (yytname) / sizeof (char *));
		       yyx++)
		    if (yycheck[yyx + yyn] == yyx)
		      {
			const char *yyq = ! yycount ? ", expecting " : " or ";
			yyp = yystpcpy (yyp, yyq);
			yyp = yystpcpy (yyp, yytname[yyx]);
			yycount++;
		      }
		}
	      yyerror (yymsg);
	      YYSTACK_FREE (yymsg);
	    }
	  else
	    yyerror ("parse error; also virtual memory exhausted");
	}
      else
#endif /* defined (YYERROR_VERBOSE) */
	yyerror ("parse error");
    }
  goto yyerrlab1;


/*--------------------------------------------------.
| yyerrlab1 -- error raised explicitly by an action |
`--------------------------------------------------*/
yyerrlab1:
  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
	 error, discard it.  */

      /* return failure if at end of input */
      if (yychar == YYEOF)
	YYABORT;
      YYDPRINTF ((stderr, "Discarding token %d (%s).\n",
		  yychar, yytname[yychar1]));
      yychar = YYEMPTY;
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */

  yyerrstatus = 3;		/* Each real token shifted decrements this */

  goto yyerrhandle;


/*-------------------------------------------------------------------.
| yyerrdefault -- current state does not do anything special for the |
| error token.                                                       |
`-------------------------------------------------------------------*/
yyerrdefault:
#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */

  /* If its default is to accept any token, ok.  Otherwise pop it.  */
  yyn = yydefact[yystate];
  if (yyn)
    goto yydefault;
#endif


/*---------------------------------------------------------------.
| yyerrpop -- pop the current state because it cannot handle the |
| error token                                                    |
`---------------------------------------------------------------*/
yyerrpop:
  if (yyssp == yyss)
    YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#if YYLSP_NEEDED
  yylsp--;
#endif

#if YYDEBUG
  if (yydebug)
    {
      short *yyssp1 = yyss - 1;
      YYFPRINTF (stderr, "Error: state stack now");
      while (yyssp1 != yyssp)
	YYFPRINTF (stderr, " %d", *++yyssp1);
      YYFPRINTF (stderr, "\n");
    }
#endif

/*--------------.
| yyerrhandle.  |
`--------------*/
yyerrhandle:
  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    goto yyerrdefault;

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    goto yyerrdefault;

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	goto yyerrpop;
      yyn = -yyn;
      goto yyreduce;
    }
  else if (yyn == 0)
    goto yyerrpop;

  if (yyn == YYFINAL)
    YYACCEPT;

  YYDPRINTF ((stderr, "Shifting error token, "));

  *++yyvsp = yylval;
#if YYLSP_NEEDED
  *++yylsp = yylloc;
#endif

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturn;

/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturn;

/*---------------------------------------------.
| yyoverflowab -- parser overflow comes here.  |
`---------------------------------------------*/
yyoverflowlab:
  yyerror ("parser stack overflow");
  yyresult = 2;
  /* Fall through.  */

yyreturn:
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif
  return yyresult;
}
#line 424 "lsys.y"


void yyerror(char *msg) {
    std::cout << std::flush;
    std::cerr << msg << " at line " << lexline << ", column "
	 << lexcol << "\n" << std::flush;
}


#ifdef sun
// Probably should be #ifndef _USES_BISON_ or some such
#ifndef __GNUG__
// /usr/lib/yaccpar is old-C and calls to free() should cast to (int *).
// Since there's no way to do that, we overload free() instead.
// This probably applies to other System V yaccs, too.
void free(int *ip) {
    free((char *)ip);
}

void free(YYSTYPE *yp) {
    free((char *)yp);
}
#endif /*!__GNUG__*/
#endif /*sun*/
